# Generated by Django 6.0.3 on 2026-04-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_department_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dean', 'Dean'), ('hod', 'Head of Department'), ('doctor', 'Doctor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
