# Generated by Django 6.0.3 on 2026-04-27

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                condition=Q(role='hod'),
                fields=('department',),
                name='unique_hod_per_department',
            ),
        ),
    ]
