# Generated by Django 6.0.3 on 2026-06-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_must_change_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_hod_per_department',
        ),
        migrations.AddField(
            model_name='user',
            name='has_changed_username',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('role', 'hod')), fields=('department',), name='unique_hod_per_department'),
        ),
    ]
