# Generated by Django 6.0.3 on 2026-07-02 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_unique_hod_per_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Reference',
                'verbose_name_plural': 'Student References',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['university_id'], name='accounts_st_univers_161c26_idx')],
            },
        ),
    ]
