# Generated by Django 6.0.3 on 2026-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=50)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['university_id', '-created_at'], name='accounts_ot_univers_1d0b7d_idx'), models.Index(fields=['session_token'], name='accounts_ot_session_c11a10_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_2f08f4_idx')],
            },
        ),
    ]
