# Generated by Django 6.0.3 on 2026-07-04 14:06

import django.db.models.deletion
import grades.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0004_committee_discussion_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_source', models.CharField(choices=[('IdeaApplication', 'IdeaApplication'), ('StudentIdeaProposal', 'StudentIdeaProposal')], db_index=True, max_length=30)),
                ('project_id', models.PositiveIntegerField(db_index=True)),
                ('semester', models.CharField(db_index=True, default='', max_length=50)),
                ('committee_type', models.CharField(choices=[('seminar_1', 'Seminar 1'), ('seminar_2', 'Seminar 2'), ('technical', 'Technical'), ('final_discussion', 'Final Discussion')], db_index=True, max_length=25)),
                ('score_main', grades.models.EncryptedScoreField(blank=True, max_length=512, null=True)),
                ('score_report', grades.models.EncryptedScoreField(blank=True, max_length=512, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='committees.committee')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_source', 'project_id', 'committee_type'],
            },
        ),
        migrations.CreateModel(
            name='GradeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=20, null=True)),
                ('new_value', models.CharField(blank=True, max_length=20, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='grades.projectgrade')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_source', models.CharField(choices=[('IdeaApplication', 'IdeaApplication'), ('StudentIdeaProposal', 'StudentIdeaProposal')], db_index=True, max_length=30)),
                ('project_id', models.PositiveIntegerField(db_index=True)),
                ('semester', models.CharField(db_index=True, default='', max_length=50)),
                ('file', models.FileField(upload_to=grades.models._report_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectgrade',
            index=models.Index(fields=['semester', 'project_source', 'project_id'], name='grades_proj_semeste_1ec0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgrade',
            index=models.Index(fields=['committee_type', 'semester'], name='grades_proj_committ_11763c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgrade',
            unique_together={('project_source', 'project_id', 'committee_type')},
        ),
        migrations.AddIndex(
            model_name='projectreport',
            index=models.Index(fields=['semester', 'project_source', 'project_id'], name='grades_proj_semeste_913d94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectreport',
            unique_together={('project_source', 'project_id')},
        ),
    ]
