# Generated by Django 6.0.3 on 2026-07-04 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committee_discussion_duration'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgrade',
            options={'ordering': ['project_source', 'project_id', 'committee_type', 'student']},
        ),
        migrations.AlterUniqueTogether(
            name='projectgrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectgrade',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectgrade',
            unique_together={('project_source', 'project_id', 'committee_type', 'student')},
        ),
        migrations.AddIndex(
            model_name='projectgrade',
            index=models.Index(fields=['student', 'committee_type'], name='grades_proj_student_86f107_idx'),
        ),
    ]
