# Generated by Django 6.0.3 on 2026-07-05 03:09

import django.db.models.deletion
import grades.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committee_discussion_duration'),
        ('grades', '0002_alter_projectgrade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeGradingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.BooleanField(default=False, help_text='عندما True: كل أعضاء اللجنة يُدخلون علاماتهم والناتج هو المتوسط.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_mode', to='committees.committee')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_mode_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Grading Mode',
            },
        ),
        migrations.CreateModel(
            name='DoctorGradeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_source', models.CharField(choices=[('IdeaApplication', 'IdeaApplication'), ('StudentIdeaProposal', 'StudentIdeaProposal')], max_length=30)),
                ('project_id', models.PositiveIntegerField()),
                ('committee_type', models.CharField(max_length=25)),
                ('score_main', grades.models.EncryptedScoreField(blank=True, max_length=512, null=True)),
                ('score_report', grades.models.EncryptedScoreField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_drafts', to='committees.committee')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_grade_drafts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_grade_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['committee', 'project_source', 'project_id', 'student', 'doctor'],
                'unique_together': {('committee', 'project_source', 'project_id', 'student', 'committee_type', 'doctor')},
            },
        ),
    ]
