# Generated by Django 6.0.3 on 2026-04-13 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('idea_submitted', 'Idea Submitted'), ('idea_approved', 'Idea Approved'), ('idea_rejected', 'Idea Rejected'), ('proposal_submitted', 'Proposal Submitted'), ('proposal_approved_sup', 'Proposal Approved by Supervisor'), ('proposal_approved_hod', 'Proposal Approved by HoD'), ('proposal_rejected', 'Proposal Rejected'), ('proposal_assigned', 'Proposal Assigned'), ('application_submitted', 'Application Submitted'), ('application_approved_doc', 'Application Approved by Doctor'), ('application_approved_hod', 'Application Approved by HoD'), ('application_rejected', 'Application Rejected'), ('application_registered', 'Application Registered'), ('invitation_received', 'Invitation Received'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_rejected', 'Invitation Rejected')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
