# Generated by Django 6.0.3 on 2026-05-03 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0003_activitylog_project_man_board_i_3bf52e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(db_index=True, max_length=40)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_username', models.CharField(blank=True, max_length=100)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('authored_date', models.DateTimeField()),
                ('committed_date', models.DateTimeField()),
                ('added_lines', models.PositiveIntegerField(default=0)),
                ('removed_lines', models.PositiveIntegerField(default=0)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-committed_date'],
            },
        ),
        migrations.CreateModel(
            name='GitLabCommitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gitlab_integration.gitlabcommit')),
            ],
        ),
        migrations.CreateModel(
            name='GitLabProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, default='', max_length=200)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('webhook_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gitlab_project_id', models.PositiveIntegerField()),
                ('gitlab_project_path', models.CharField(max_length=255)),
                ('web_url', models.URLField()),
                ('ssh_url', models.URLField(blank=True)),
                ('http_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_project', to='project_management.projectboard')),
            ],
        ),
        migrations.AddField(
            model_name='gitlabcommit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='gitlab_integration.gitlabproject'),
        ),
        migrations.CreateModel(
            name='GitLabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_name', models.CharField(blank=True, default='', max_length=200)),
                ('gitlab_email', models.EmailField(blank=True, default='', max_length=254)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('access_token', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gitlab_user_id', models.PositiveIntegerField()),
                ('gitlab_username', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gitlabproject',
            index=models.Index(fields=['gitlab_project_id'], name='gitlab_inte_gitlab__88a63f_idx'),
        ),
        migrations.AddIndex(
            model_name='gitlabcommit',
            index=models.Index(fields=['project', '-committed_date'], name='gitlab_inte_project_1a1007_idx'),
        ),
        migrations.AddIndex(
            model_name='gitlabcommit',
            index=models.Index(fields=['author_username', 'project'], name='gitlab_inte_author__892486_idx'),
        ),
        migrations.AddIndex(
            model_name='gitlabuser',
            index=models.Index(fields=['gitlab_user_id'], name='gitlab_inte_gitlab__a5c323_idx'),
        ),
    ]
