# Generated by Django 6.0.3 on 2026-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_integration', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitlabuser',
            old_name='created_at',
            new_name='linked_at',
        ),
        migrations.RemoveField(
            model_name='gitlabproject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gitlabuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='gitlabcommit',
            name='author_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gitlabcommit',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gitlabproject',
            name='http_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gitlabproject',
            name='ssh_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
