# Generated by Django 6.0.3 on 2026-05-24 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_integration', '0004_add_updated_at_and_web_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabcommit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gitlabproject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='gitlabcommit',
            unique_together={('project', 'sha')},
        ),
    ]
