# Generated by Django 6.0.3 on 2026-05-24 13:05

import gitlab_integration.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_integration', '0005_alter_gitlabcommit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabuser',
            name='access_token',
            field=gitlab_integration.models.EncryptedCharField(blank=True, default='', max_length=500),
        ),
    ]
