# Generated by Django 6.0.3 on 2026-04-13 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.CharField(choices=[('software_engineering', 'Software Engineering'), ('artificial_intelligence', 'Artificial Intelligence'), ('information_security', 'Information Security'), ('communications', 'Communications'), ('control_robotics', 'Control & Robotics')], max_length=50)),
                ('required_skills', models.CharField(help_text='Comma-separated tags', max_length=500)),
                ('max_team_size', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
