# Generated by Django 6.0.3 on 2026-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectidea_required_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
