# Generated by Django 6.0.3 on 2026-04-13 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectidea_rejection_reason_projectidea_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_doctor', 'Pending Doctor Approval'), ('pending_hod', 'Pending HoD Approval'), ('registered', 'Registered'), ('rejected', 'Rejected')], default='pending_doctor', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.projectidea')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='idea_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('idea', 'student')},
            },
        ),
    ]
