# Generated by Django 6.0.3 on 2026-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_ideaapplication_team_size_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaapplication',
            name='status',
            field=models.CharField(choices=[('awaiting_members', 'Awaiting Member Confirmation'), ('pending_doctor', 'Pending Doctor Approval'), ('pending_hod', 'Pending HoD Approval'), ('registered', 'Registered'), ('rejected', 'Rejected')], default='pending_doctor', max_length=20),
        ),
    ]
