# Generated by Django 6.0.3 on 2026-04-13 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_ideaapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentideaproposal',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentideaproposal',
            name='team_size_reason',
            field=models.TextField(blank=True, help_text='Required when team_size < 2 or > 3'),
        ),
        migrations.AlterField(
            model_name='studentideaproposal',
            name='status',
            field=models.CharField(choices=[('awaiting_members', 'Awaiting Member Confirmation'), ('pending_supervisor', 'Pending Supervisor Approval'), ('pending_hod', 'Pending HoD Review'), ('assigned', 'Assigned'), ('rejected', 'Rejected')], default='pending_supervisor', max_length=25),
        ),
        migrations.CreateModel(
            name='ProposalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_invitations', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.studentideaproposal')),
            ],
            options={
                'unique_together': {('proposal', 'invitee')},
            },
        ),
    ]
