# Generated by Django 6.0.3 on 2026-04-27

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_studentideaproposal_student'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ideaapplication',
            constraint=models.UniqueConstraint(
                condition=Q(status='registered'),
                fields=('idea',),
                name='unique_registered_application_per_idea',
            ),
        ),
    ]
