# Generated by Django 6.0.3 on 2026-04-28 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_ideaapplication_unique_registered_per_idea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ideaapplication',
            index=models.Index(fields=['student', 'status'], name='projects_id_student_09f121_idx'),
        ),
        migrations.AddIndex(
            model_name='ideaapplication',
            index=models.Index(fields=['idea', 'status'], name='projects_id_idea_id_ce6706_idx'),
        ),
        migrations.AddIndex(
            model_name='ideaapplication',
            index=models.Index(fields=['status', '-created_at'], name='projects_id_status_5d202e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectapplication',
            index=models.Index(fields=['student', 'status'], name='projects_pr_student_c7bca1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectidea',
            index=models.Index(fields=['doctor', 'status'], name='projects_pr_doctor__673e03_idx'),
        ),
        migrations.AddIndex(
            model_name='projectidea',
            index=models.Index(fields=['department', 'status', '-created_at'], name='projects_pr_departm_52b9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectidea',
            index=models.Index(fields=['status', '-created_at'], name='projects_pr_status_874077_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalinvitation',
            index=models.Index(fields=['invitee', 'status'], name='projects_pr_invitee_b1e6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalinvitation',
            index=models.Index(fields=['proposal', 'status'], name='projects_pr_proposa_796b33_idx'),
        ),
        migrations.AddIndex(
            model_name='studentideaproposal',
            index=models.Index(fields=['student', 'status'], name='projects_st_student_1b9c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentideaproposal',
            index=models.Index(fields=['supervisor', 'status', '-created_at'], name='projects_st_supervi_7a366c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentideaproposal',
            index=models.Index(fields=['department', 'status', '-created_at'], name='projects_st_departm_76fea2_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['invitee', 'status'], name='projects_te_invitee_a92ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['application', 'status'], name='projects_te_applica_1786ba_idx'),
        ),
    ]
