# Generated by Django 6.0.3 on 2026-05-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_ideaapplication_projects_id_student_09f121_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaapplication',
            name='status',
            field=models.CharField(choices=[('awaiting_members', 'Awaiting Member Confirmation'), ('pending_doctor', 'Pending Doctor Approval'), ('pending_hod', 'Pending HoD Approval'), ('registered', 'Registered'), ('rejected', 'Rejected'), ('rejected_insufficient_members', 'Rejected - Insufficient Members')], default='pending_doctor', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('rejected_insufficient_members', 'Rejected - Insufficient Members')], default='accepted', max_length=35),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=35),
        ),
    ]
