# Generated by Django 6.0.3 on 2026-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_ideaapplication_team_size_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentideaproposal',
            name='team_size_reason',
            field=models.TextField(blank=True, help_text='Required when team_size is 1 or 4'),
        ),
    ]
