# Generated by Django 6.0.3 on 2026-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_studentideaproposal_team_size_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaapplication',
            name='status',
            field=models.CharField(choices=[('awaiting_members', 'Awaiting Member Confirmation'), ('pending_doctor', 'Pending Doctor Approval'), ('pending_hod', 'Pending HoD Approval'), ('registered', 'Registered'), ('rejected', 'Rejected'), ('rejected_insufficient_members', 'Rejected - Insufficient Members')], max_length=30),
        ),
    ]
