# Generated by Django 6.0.3 on 2026-06-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectidea_allow_hod'),
        ('projects', '0014_alter_ideaapplication_status'),
    ]

    operations = [
    ]
