# Generated by Django 6.0.3 on 2026-06-22 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_merge_20260622_2043'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaapplication',
            name='project_type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('graduation_1', 'Graduation 1'), ('graduation_2', 'Graduation 2')], default='seasonal', max_length=20),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='project_type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('graduation_1', 'Graduation 1'), ('graduation_2', 'Graduation 2')], default='seasonal', max_length=20),
        ),
        migrations.AddField(
            model_name='studentideaproposal',
            name='project_type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('graduation_1', 'Graduation 1'), ('graduation_2', 'Graduation 2')], default='seasonal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ideaapplication',
            name='status',
            field=models.CharField(choices=[('awaiting_members', 'Awaiting Member Confirmation'), ('pending_doctor', 'Pending Doctor Approval'), ('pending_hod', 'Pending HoD Approval'), ('registered', 'Registered'), ('rejected', 'Rejected'), ('rejected_insufficient_members', 'Rejected - Insufficient Members')], default='pending_doctor', max_length=30),
        ),
        migrations.AlterField(
            model_name='ideaapplication',
            name='team_size_reason',
            field=models.TextField(blank=True, help_text='Required when team_size < 2 or > 3'),
        ),
        migrations.AddConstraint(
            model_name='studentideaproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_members', 'pending_supervisor', 'pending_hod', 'assigned'])), fields=('student',), name='unique_active_proposal_per_student'),
        ),
    ]
