# Generated by Django 5.1.6 on 2026-06-28 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _operational_status_for_count(active_count):
    if active_count == 1:
        return 'solo'
    if active_count > 1:
        return 'active'
    return 'inactive'


def backfill_project_participations(apps, schema_editor):
    ProjectParticipation = apps.get_model('projects', 'ProjectParticipation')
    IdeaApplication = apps.get_model('projects', 'IdeaApplication')
    TeamInvitation = apps.get_model('projects', 'TeamInvitation')
    StudentIdeaProposal = apps.get_model('projects', 'StudentIdeaProposal')
    ProposalInvitation = apps.get_model('projects', 'ProposalInvitation')

    for application in IdeaApplication.objects.filter(status='registered').iterator():
        student_ids = set()
        if application.student_id:
            ProjectParticipation.objects.get_or_create(
                student_id=application.student_id,
                idea_application_id=application.id,
                defaults={
                    'project_source': 'idea_application',
                    'role': 'leader',
                    'status': 'active',
                },
            )
            student_ids.add(application.student_id)

        accepted_invitees = TeamInvitation.objects.filter(
            application_id=application.id,
            status='accepted',
        ).values_list('invitee_id', flat=True)
        for invitee_id in accepted_invitees:
            if invitee_id in student_ids:
                continue
            ProjectParticipation.objects.get_or_create(
                student_id=invitee_id,
                idea_application_id=application.id,
                defaults={
                    'project_source': 'idea_application',
                    'role': 'member',
                    'status': 'active',
                },
            )
            student_ids.add(invitee_id)

        application.operational_status = _operational_status_for_count(len(student_ids))
        application.save(update_fields=['operational_status'])

    for proposal in StudentIdeaProposal.objects.filter(status='assigned').iterator():
        student_ids = set()
        if proposal.student_id:
            ProjectParticipation.objects.get_or_create(
                student_id=proposal.student_id,
                student_proposal_id=proposal.id,
                defaults={
                    'project_source': 'student_proposal',
                    'role': 'leader',
                    'status': 'active',
                },
            )
            student_ids.add(proposal.student_id)

        accepted_invitees = ProposalInvitation.objects.filter(
            proposal_id=proposal.id,
            status='accepted',
        ).values_list('invitee_id', flat=True)
        for invitee_id in accepted_invitees:
            if invitee_id in student_ids:
                continue
            ProjectParticipation.objects.get_or_create(
                student_id=invitee_id,
                student_proposal_id=proposal.id,
                defaults={
                    'project_source': 'student_proposal',
                    'role': 'member',
                    'status': 'active',
                },
            )
            student_ids.add(invitee_id)

        proposal.operational_status = _operational_status_for_count(len(student_ids))
        proposal.save(update_fields=['operational_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_studentideaproposal_co_supervisors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaapplication',
            name='operational_status',
            field=models.CharField(choices=[('active', 'Active'), ('partial_team', 'Partial Team'), ('solo', 'Solo'), ('fully_withdrawn', 'Fully Withdrawn'), ('fully_failed', 'Fully Failed'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='studentideaproposal',
            name='operational_status',
            field=models.CharField(choices=[('active', 'Active'), ('partial_team', 'Partial Team'), ('solo', 'Solo'), ('fully_withdrawn', 'Fully Withdrawn'), ('fully_failed', 'Fully Failed'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_source', models.CharField(choices=[('idea_application', 'Doctor Idea Application'), ('student_proposal', 'Student Idea Proposal')], max_length=24)),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], default='active', max_length=12)),
                ('status_reason', models.TextField(blank=True)),
                ('status_notes', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.ideaapplication')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_project_participations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to=settings.AUTH_USER_MODEL)),
                ('student_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.studentideaproposal')),
            ],
            options={
                'ordering': ['student__username', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_source', models.CharField(choices=[('idea_application', 'Doctor Idea Application'), ('student_proposal', 'Student Idea Proposal')], max_length=24)),
                ('previous_status', models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], max_length=12)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('student_project_status_marked_failed', 'Student project status marked failed'), ('student_project_status_marked_withdrawn', 'Student project status marked withdrawn'), ('student_project_status_reversed_to_active', 'Student project status reversed to active')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participation_status_changes', to=settings.AUTH_USER_MODEL)),
                ('idea_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation_status_logs', to='projects.ideaapplication')),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_logs', to='projects.projectparticipation')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participation_status_logs', to=settings.AUTH_USER_MODEL)),
                ('student_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation_status_logs', to='projects.studentideaproposal')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectparticipation',
            index=models.Index(fields=['student', 'status'], name='projects_pr_student_e2a792_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipation',
            index=models.Index(fields=['status', '-updated_at'], name='projects_pr_status_3d5e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipation',
            index=models.Index(fields=['project_source', 'status'], name='projects_pr_project_12ea6c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipation',
            index=models.Index(fields=['idea_application', 'status'], name='projects_pr_idea_ap_98992f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipation',
            index=models.Index(fields=['student_proposal', 'status'], name='projects_pr_student_bb569a_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectparticipation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idea_application__isnull', False), ('project_source', 'idea_application'), ('student_proposal__isnull', True)), models.Q(('idea_application__isnull', True), ('project_source', 'student_proposal'), ('student_proposal__isnull', False)), _connector='OR'), name='project_participation_exactly_one_project'),
        ),
        migrations.AddConstraint(
            model_name='projectparticipation',
            constraint=models.UniqueConstraint(condition=models.Q(('idea_application__isnull', False)), fields=('student', 'idea_application'), name='unique_student_idea_application_participation'),
        ),
        migrations.AddConstraint(
            model_name='projectparticipation',
            constraint=models.UniqueConstraint(condition=models.Q(('student_proposal__isnull', False)), fields=('student', 'student_proposal'), name='unique_student_proposal_participation'),
        ),
        migrations.AddIndex(
            model_name='projectparticipationstatuslog',
            index=models.Index(fields=['student', '-changed_at'], name='projects_pr_student_b1602f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipationstatuslog',
            index=models.Index(fields=['changed_by', '-changed_at'], name='projects_pr_changed_5baf59_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipationstatuslog',
            index=models.Index(fields=['project_source', '-changed_at'], name='projects_pr_project_0fffe3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipationstatuslog',
            index=models.Index(fields=['action_type', '-changed_at'], name='projects_pr_action__715239_idx'),
        ),
        migrations.RunPython(backfill_project_participations, migrations.RunPython.noop),
    ]
