# Generated by Django 6.0.3 on 2026-07-02 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_ideaapplication_operational_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ideaapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_members', 'pending_doctor', 'pending_hod', 'registered'])), fields=('student',), name='unique_active_application_per_student'),
        ),
    ]
