# Generated by Django 6.0.3 on 2026-04-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dy_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicform',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='formresponse',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicform',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='frequency',
            field=models.CharField(blank=True, choices=[('once', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('milestone', 'At Milestones')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this a recurring report?'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='project_board_id',
            field=models.IntegerField(blank=True, help_text='For progress reports', null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='report_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='report_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='context',
            field=models.CharField(choices=[('propose', 'Student Proposes Own Idea'), ('browse', 'Student Applies on Doctor Idea'), ('weekly_report', 'Weekly Progress Report'), ('monthly_report', 'Monthly Progress Report'), ('milestone', 'Milestone Report'), ('final_report', 'Final Project Report'), ('custom', 'Custom Report')], max_length=20),
        ),
    ]
