# Generated by Django 6.0.3 on 2026-04-28

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def backfill_field_response_snapshots(apps, schema_editor):
    FieldResponse = apps.get_model('dy_forms', 'FieldResponse')

    for response in FieldResponse.objects.select_related('field').all():
        field = response.field
        if not field:
            continue

        response.field_label = field.label
        response.field_type = field.field_type
        response.field_options = field.options or []

        if response.value_data is None:
            if field.field_type == 'checkbox':
                response.value_data = [value for value in (response.value or '').split(',') if value]
            else:
                response.value_data = response.value or ''

        response.save(update_fields=['field_label', 'field_type', 'field_options', 'value_data'])


class Migration(migrations.Migration):

    dependencies = [
        ('dy_forms', '0002_alter_dynamicform_options_alter_formresponse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldresponse',
            name='field_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fieldresponse',
            name='field_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fieldresponse',
            name='field_type',
            field=models.CharField(blank=True, choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('date', 'Date'), ('file', 'File Upload')], max_length=10),
        ),
        migrations.AddField(
            model_name='fieldresponse',
            name='value_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_field_response_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fieldresponse',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='dy_forms.formfield'),
        ),
        migrations.AddConstraint(
            model_name='dynamicform',
            constraint=models.UniqueConstraint(fields=('department', 'context'), name='unique_dynamic_form_department_context'),
        ),
        migrations.AddConstraint(
            model_name='fieldresponse',
            constraint=models.UniqueConstraint(condition=Q(field__isnull=False), fields=('response', 'field'), name='unique_field_response_per_field'),
        ),
    ]
