# Generated by Django 6.0.3 on 2026-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dy_forms', '0003_fieldresponse_snapshots_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='form_uploads/%Y/%m/'),
        ),
    ]
