import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const api = vi.hoisted(() => ({ requestEmailChange:vi.fn(), confirmEmailChange:vi.fn(), studentSelfRegister:vi.fn() }));
vi.mock('../../api.jsx',()=>({ ...api }));
const theme = vi.hoisted(()=>({ current:'light' }));
vi.mock('../../ThemeContext.jsx',()=>({ useTheme:()=>({theme:theme.current}) }));
import ChangeEmail from '../ChangeEmail.jsx';
import SelfRegister from '../SelfRegister.jsx';

beforeEach(()=>{ vi.clearAllMocks(); theme.current='light'; api.requestEmailChange.mockResolvedValue({data:{session_token:'tok-1',email_hint:'n***@mail.com',expires_in_seconds:120,message:'CODE SENT'}}); api.confirmEmailChange.mockResolvedValue({data:{email:'new@mail.com',message:'EMAIL CHANGED'}}); api.studentSelfRegister.mockResolvedValue({data:{username:'s100',role:'student',must_change_password:false,must_change_username:false,department:'software_engineering'}}); });

async function requestEmail(){ render(<ChangeEmail user={{email:'old@mail.com'}}/>); fireEvent.change(screen.getByPlaceholderText('name@example.com'),{target:{value:'  new@mail.com  '}}); fireEvent.change(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input'),{target:{value:'secret'}}); fireEvent.click(screen.getByRole('button',{name:'إرسال رمز التحقق'})); await screen.findByRole('heading',{name:'أدخل رمز التحقق'}); }

describe('ChangeEmail account security contract',()=>{
  it('renders current email',()=>{ render(<ChangeEmail user={{email:'old@mail.com'}}/>); expect(screen.getByText('old@mail.com')).toBeTruthy(); });
  it('shows fallback when user has no email',()=>{ render(<ChangeEmail user={{}}/>); expect(screen.getByText('لا يوجد بريد إلكتروني مرتبط')).toBeTruthy(); });
  it('renders request-step controls',()=>{ render(<ChangeEmail/>); expect(screen.getByPlaceholderText('name@example.com')).toBeTruthy(); expect(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input')).toBeTruthy(); });
  it('calls optional cancel callback',()=>{ const fn=vi.fn(); render(<ChangeEmail onBack={fn}/>); fireEvent.click(screen.getByRole('button',{name:'إلغاء'})); expect(fn).toHaveBeenCalledOnce(); });
  it('hides cancel when callback absent',()=>{ render(<ChangeEmail/>); expect(screen.queryByRole('button',{name:'إلغاء'})).toBeNull(); });
  it('trims new email before request',async()=>{ await requestEmail(); expect(api.requestEmailChange).toHaveBeenCalledWith('new@mail.com','secret'); });
  it('moves to verification after request',async()=>{ await requestEmail(); expect(screen.getByRole('heading',{name:'أدخل رمز التحقق'})).toBeTruthy(); });
  it('shows server email hint',async()=>{ await requestEmail(); expect(screen.getByText('n***@mail.com')).toBeTruthy(); });
  it('shows request success message',async()=>{ await requestEmail(); expect(screen.getByText('CODE SENT')).toBeTruthy(); });
  it('uses trimmed new email as hint fallback',async()=>{ api.requestEmailChange.mockResolvedValue({data:{session_token:'tok',expires_in_seconds:60}}); render(<ChangeEmail/>); fireEvent.change(screen.getByPlaceholderText('name@example.com'),{target:{value:' x@y.com '}}); fireEvent.change(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input'),{target:{value:'p'}}); fireEvent.click(screen.getByRole('button',{name:'إرسال رمز التحقق'})); expect(await screen.findByText('x@y.com')).toBeTruthy(); });
  it('uses ten-minute expiry fallback',async()=>{ api.requestEmailChange.mockResolvedValue({data:{session_token:'tok'}}); render(<ChangeEmail/>); fireEvent.change(screen.getByPlaceholderText('name@example.com'),{target:{value:'x@y.com'}}); fireEvent.change(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input'),{target:{value:'p'}}); fireEvent.click(screen.getByRole('button',{name:'إرسال رمز التحقق'})); expect(await screen.findByText('10:00')).toBeTruthy(); });
  it('shows two-minute expiry from backend',async()=>{ await requestEmail(); expect(screen.getByText('2:00')).toBeTruthy(); });
  it('counts expiry down each second',async()=>{ await requestEmail(); await new Promise((resolve)=>setTimeout(resolve,1050)); expect(screen.getByText('1:59')).toBeTruthy(); });
  it('digits-only verification code',async()=>{ await requestEmail(); const input=screen.getByPlaceholderText('000000'); fireEvent.change(input,{target:{value:'1a2b345678'}}); expect(input.value).toBe('123456'); });
  it('verify button stays disabled before six digits',async()=>{ await requestEmail(); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'12345'}}); expect(screen.getByRole('button',{name:'تأكيد البريد الجديد'}).disabled).toBe(true); });
  it('verify button enables at six digits',async()=>{ await requestEmail(); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123456'}}); expect(screen.getByRole('button',{name:'تأكيد البريد الجديد'}).disabled).toBe(false); });
  it('confirms using session token and trimmed code',async()=>{ await requestEmail(); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123456'}}); fireEvent.click(screen.getByRole('button',{name:'تأكيد البريد الجديد'})); await waitFor(()=>expect(api.confirmEmailChange).toHaveBeenCalledWith('tok-1','123456')); });
  it('calls changed callback with confirmed email',async()=>{ const onChanged=vi.fn(); render(<ChangeEmail user={{email:'old'}} onChanged={onChanged}/>); fireEvent.change(screen.getByPlaceholderText('name@example.com'),{target:{value:'new@mail.com'}}); fireEvent.change(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input'),{target:{value:'p'}}); fireEvent.click(screen.getByRole('button',{name:'إرسال رمز التحقق'})); await screen.findByPlaceholderText('000000'); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123456'}}); fireEvent.click(screen.getByRole('button',{name:'تأكيد البريد الجديد'})); await waitFor(()=>expect(onChanged).toHaveBeenCalledWith('new@mail.com')); });
  it('shows done state after confirmation',async()=>{ await requestEmail(); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123456'}}); fireEvent.click(screen.getByRole('button',{name:'تأكيد البريد الجديد'})); expect(await screen.findByRole('heading',{name:'تم تحديث البريد الإلكتروني'})).toBeTruthy(); });
  it('returns from done state with callback',async()=>{ const onBack=vi.fn(); render(<ChangeEmail onBack={onBack}/>); fireEvent.change(screen.getByPlaceholderText('name@example.com'),{target:{value:'x@y.com'}}); fireEvent.change(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input'),{target:{value:'p'}}); fireEvent.click(screen.getByRole('button',{name:'إرسال رمز التحقق'})); await screen.findByPlaceholderText('000000'); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123456'}}); fireEvent.click(screen.getByRole('button',{name:'تأكيد البريد الجديد'})); fireEvent.click(await screen.findByRole('button',{name:'العودة'})); expect(onBack).toHaveBeenCalledOnce(); });
  it('returns from verify to request step',async()=>{ await requestEmail(); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123'}}); fireEvent.click(screen.getByRole('button',{name:'تغيير البريد أو إعادة الإرسال'})); expect(screen.getByPlaceholderText('name@example.com')).toBeTruthy(); expect(screen.queryByPlaceholderText('000000')).toBeNull(); });
  it('shows backend request error',async()=>{ api.requestEmailChange.mockRejectedValue({response:{data:{error:'EMAIL USED'}}}); render(<ChangeEmail/>); fireEvent.change(screen.getByPlaceholderText('name@example.com'),{target:{value:'used@mail.com'}}); fireEvent.change(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input'),{target:{value:'secret'}}); fireEvent.click(screen.getByRole('button',{name:'إرسال رمز التحقق'})); expect(await screen.findByText('EMAIL USED')).toBeTruthy(); });
  it('shows generic request error',async()=>{ api.requestEmailChange.mockRejectedValue(new Error('x')); render(<ChangeEmail/>); fireEvent.change(screen.getByPlaceholderText('name@example.com'),{target:{value:'new@mail.com'}}); fireEvent.change(screen.getByText('كلمة المرور الحالية').parentElement.querySelector('input'),{target:{value:'secret'}}); fireEvent.click(screen.getByRole('button',{name:'إرسال رمز التحقق'})); expect(await screen.findByText('تعذر إرسال رمز التحقق.')).toBeTruthy(); });
  it('shows backend confirm error',async()=>{ api.confirmEmailChange.mockRejectedValue({response:{data:{error:'BAD CODE'}}}); await requestEmail(); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123456'}}); fireEvent.click(screen.getByRole('button',{name:'تأكيد البريد الجديد'})); expect(await screen.findByText('BAD CODE')).toBeTruthy(); });
  it('shows generic confirm error',async()=>{ api.confirmEmailChange.mockRejectedValue(new Error('x')); await requestEmail(); fireEvent.change(screen.getByPlaceholderText('000000'),{target:{value:'123456'}}); fireEvent.click(screen.getByRole('button',{name:'تأكيد البريد الجديد'})); expect(await screen.findByText('تعذر تأكيد البريد الإلكتروني.')).toBeTruthy(); });
});

describe('SelfRegister account bootstrap contract',()=>{
  it('renders verification heading',()=>{ render(<SelfRegister onRegistered={()=>{}}/>); expect(screen.getByRole('heading',{name:'تحقق من الطالب'})).toBeTruthy(); });
  it.each(['انضم للبوابة','تحقق آمن','وصول فوري','جاهز للبدء'])('shows branding copy %s',(text)=>{ render(<SelfRegister onRegistered={()=>{}}/>); expect(screen.getByText(text)).toBeTruthy(); });
  it('renders university-id field',()=>{ render(<SelfRegister onRegistered={()=>{}}/>); expect(screen.getByLabelText('الرقم الجامعي')).toBeTruthy(); });
  it('renders password field',()=>{ render(<SelfRegister onRegistered={()=>{}}/>); expect(screen.getByLabelText('كلمة المرور')).toBeTruthy(); expect(screen.getByLabelText('كلمة المرور').type).toBe('password'); });
  it('calls back to login',()=>{ const fn=vi.fn(); render(<SelfRegister onRegistered={()=>{}} onBack={fn}/>); fireEvent.click(screen.getByRole('button',{name:/العودة لتسجيل الدخول/})); expect(fn).toHaveBeenCalledOnce(); });
  it('updates university id',()=>{ render(<SelfRegister onRegistered={()=>{}}/>); fireEvent.change(screen.getByLabelText('الرقم الجامعي'),{target:{value:'20201234'}}); expect(screen.getByLabelText('الرقم الجامعي').value).toBe('20201234'); });
  it('updates password',()=>{ render(<SelfRegister onRegistered={()=>{}}/>); fireEvent.change(screen.getByLabelText('كلمة المرور'),{target:{value:'Secret'}}); expect(screen.getByLabelText('كلمة المرور').value).toBe('Secret'); });
  it('submits credentials exactly',async()=>{ const fn=vi.fn(); render(<SelfRegister onRegistered={fn}/>); fireEvent.change(screen.getByLabelText('الرقم الجامعي'),{target:{value:'20201234'}}); fireEvent.change(screen.getByLabelText('كلمة المرور'),{target:{value:'Secret'}}); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); await waitFor(()=>expect(api.studentSelfRegister).toHaveBeenCalledWith('20201234','Secret')); });
  it('maps successful response to session user',async()=>{ const fn=vi.fn(); render(<SelfRegister onRegistered={fn}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); await waitFor(()=>expect(fn).toHaveBeenCalledWith({username:'s100',role:'student',must_change_password:false,must_change_username:false,department:'software_engineering'})); });
  it('falls back username to entered university id',async()=>{ api.studentSelfRegister.mockResolvedValue({data:{}}); const fn=vi.fn(); render(<SelfRegister onRegistered={fn}/>); fireEvent.change(screen.getByLabelText('الرقم الجامعي'),{target:{value:'20209999'}}); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); await waitFor(()=>expect(fn).toHaveBeenCalledWith(expect.objectContaining({username:'20209999'}))); });
  it('falls back role to student',async()=>{ api.studentSelfRegister.mockResolvedValue({data:{}}); const fn=vi.fn(); render(<SelfRegister onRegistered={fn}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); await waitFor(()=>expect(fn).toHaveBeenCalledWith(expect.objectContaining({role:'student'}))); });
  it('defaults both forced-change flags to true',async()=>{ api.studentSelfRegister.mockResolvedValue({data:{}}); const fn=vi.fn(); render(<SelfRegister onRegistered={fn}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); await waitFor(()=>expect(fn).toHaveBeenCalledWith(expect.objectContaining({must_change_password:true,must_change_username:true}))); });
  it('defaults department to blank',async()=>{ api.studentSelfRegister.mockResolvedValue({data:{}}); const fn=vi.fn(); render(<SelfRegister onRegistered={fn}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); await waitFor(()=>expect(fn).toHaveBeenCalledWith(expect.objectContaining({department:''}))); });
  it('shows loading label while verification pending',async()=>{ api.studentSelfRegister.mockReturnValue(new Promise(()=>{})); render(<SelfRegister onRegistered={()=>{}}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); expect(await screen.findByText('جاري التحقق...')).toBeTruthy(); expect(screen.getByRole('button',{name:/جاري التحقق/}).disabled).toBe(true); });
  it('shows backend registration error',async()=>{ api.studentSelfRegister.mockRejectedValue({response:{data:{error:'NOT ELIGIBLE'}}}); render(<SelfRegister onRegistered={()=>{}}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); expect((await screen.findByRole('alert')).textContent).toContain('NOT ELIGIBLE'); });
  it('shows generic registration error',async()=>{ api.studentSelfRegister.mockRejectedValue(new Error('network')); render(<SelfRegister onRegistered={()=>{}}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); expect((await screen.findByRole('alert')).textContent).toContain('Verification failed. Please try again.'); });
  it('reenables submit after failure',async()=>{ api.studentSelfRegister.mockRejectedValue(new Error('x')); render(<SelfRegister onRegistered={()=>{}}/>); fireEvent.click(screen.getByRole('button',{name:'تحقق وادخل للبوابة'})); await screen.findByRole('alert'); expect(screen.getByRole('button',{name:'تحقق وادخل للبوابة'}).disabled).toBe(false); });
  it('uses current year in footer',()=>{ render(<SelfRegister onRegistered={()=>{}}/>); expect(screen.getByText(new RegExp(String(new Date().getFullYear())))).toBeTruthy(); });
  it('uses light gradient when theme is light',()=>{ const {container}=render(<SelfRegister onRegistered={()=>{}}/>); const overlays=[...container.querySelectorAll('div')].filter(d=>String(d.style.background).includes('linear-gradient')); expect(overlays.some(d=>d.style.background.includes('248, 249, 253'))).toBe(true); });
  it('uses dark gradient when theme is dark',()=>{ theme.current='dark'; const {container}=render(<SelfRegister onRegistered={()=>{}}/>); const overlays=[...container.querySelectorAll('div')].filter(d=>String(d.style.background).includes('linear-gradient')); expect(overlays.some(d=>d.style.background.includes('15, 17, 23'))).toBe(true); });
});
