import React from 'react';
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const api = vi.hoisted(()=>({ fetchHodPendingDoctorIdeas:vi.fn(), hodReviewDoctorIdea:vi.fn() }));
vi.mock('../../api.jsx',()=>({ ...api }));
import HodIdeaReview from '../HodIdeaReview.jsx';

const ideas=[
 {id:1,title:'AI Diagnosis',doctor_name:'Dr One',department:'artificial_intelligence',max_team_size:2,project_type:'graduation_1',description:'AI medical project',required_skills:'Python, ML'},
 {id:2,title:'Secure IoT',doctor_name:'Dr Two',department:'information_security',max_team_size:3,project_type:'graduation_2',description:'Security project',required_skills:'React, Security'},
 {id:3,title:'Robot Arm',doctor_name:'Dr Three',department:'control_robotics',max_team_size:2,project_type:'seasonal',description:'Robot project',required_skills:''},
];
beforeEach(()=>{ vi.clearAllMocks(); api.fetchHodPendingDoctorIdeas.mockResolvedValue({data:ideas}); api.hodReviewDoctorIdea.mockResolvedValue({data:{}}); });
function card(title){ return screen.getByText(title).closest('.bg-white'); }

describe('HoD doctor-idea review contract',()=>{
 it('renders page heading',async()=>{ render(<HodIdeaReview/>); expect(await screen.findByRole('heading',{name:'أفكار مشاريع الدكاترة'})).toBeTruthy(); });
 it('loads pending doctor ideas',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); expect(api.fetchHodPendingDoctorIdeas).toHaveBeenCalledOnce(); });
 it('shows loading state',()=>{ api.fetchHodPendingDoctorIdeas.mockReturnValue(new Promise(()=>{})); render(<HodIdeaReview/>); expect(screen.getByText('جاري تحميل الأفكار...')).toBeTruthy(); });
 it('shows load failure',async()=>{ api.fetchHodPendingDoctorIdeas.mockRejectedValue(new Error('x')); render(<HodIdeaReview/>); expect(await screen.findByText('Failed to load ideas.')).toBeTruthy(); });
 it('shows reviewed empty state',async()=>{ api.fetchHodPendingDoctorIdeas.mockResolvedValue({data:[]}); render(<HodIdeaReview/>); expect(await screen.findByText('تمت المراجعة')).toBeTruthy(); });
 it('shows empty-state guidance',async()=>{ api.fetchHodPendingDoctorIdeas.mockResolvedValue({data:[]}); render(<HodIdeaReview/>); expect(await screen.findByText(/لا توجد أفكار دكاترة معلقة/)).toBeTruthy(); });
 it('shows idea-count badge',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); expect(screen.getByText('3')).toBeTruthy(); });
 it.each(['AI Diagnosis','Secure IoT','Robot Arm'])('renders idea %s',async(title)=>{ render(<HodIdeaReview/>); expect(await screen.findByText(title)).toBeTruthy(); });
 it.each(['Dr One','Dr Two','Dr Three'])('renders doctor %s',async(name)=>{ render(<HodIdeaReview/>); expect(await screen.findByText(name)).toBeTruthy(); });
 it.each(['artificial intelligence','information security','control robotics'])('normalizes department %s',async(dep)=>{ render(<HodIdeaReview/>); expect(await screen.findByText(dep)).toBeTruthy(); });
 it('shows team-size badges',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); expect(screen.getAllByText('2 students')).toHaveLength(2); expect(screen.getByText('3 students')).toBeTruthy(); });
 it.each(['Graduation 1','Graduation 2','Seasonal'])('shows project type %s',async(type)=>{ render(<HodIdeaReview/>); expect(await screen.findByText(type)).toBeTruthy(); });
 it.each(['AI medical project','Security project','Robot project'])('renders description %s',async(text)=>{ render(<HodIdeaReview/>); expect(await screen.findByText(text)).toBeTruthy(); });
 it.each(['Python','ML','React','Security'])('splits skill %s into badge',async(skill)=>{ render(<HodIdeaReview/>); expect(await screen.findByText(skill)).toBeTruthy(); });
 it('does not render empty skill badge',async()=>{ render(<HodIdeaReview/>); await screen.findByText('Robot Arm'); expect(within(card('Robot Arm')).queryByText('Skills:',{selector:'span'})).toBeNull(); expect(screen.getAllByText('Skills:',{selector:'span'})).toHaveLength(2); expect(document.body.textContent.includes('undefined')).toBe(false); });
 it('renders approve action per idea',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); expect(screen.getAllByRole('button',{name:'Approve'})).toHaveLength(3); });
 it('renders reject action per idea',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); expect(screen.getAllByRole('button',{name:'Reject'})).toHaveLength(3); });
 it('opens approve modal',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); expect(screen.getByRole('dialog')).toBeTruthy(); expect(screen.getByRole('heading',{name:'الموافقة على الفكرة'})).toBeTruthy(); });
 it('approve modal explains publishing effect',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); expect(screen.getByText(/become available for student applications/)).toBeTruthy(); });
 it('opens reject modal with required reason field',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Reject'})); expect(screen.getByRole('heading',{name:'رفض الفكرة'})).toBeTruthy(); expect(screen.getByLabelText(/Rejection Reason/)).toBeTruthy(); });
 it('cancels review modal',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'Cancel'})); expect(screen.queryByRole('dialog')).toBeNull(); });
 it('submits approve action with empty rejection reason',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); await waitFor(()=>expect(api.hodReviewDoctorIdea).toHaveBeenCalledWith(1,{action:'approve',rejection_reason:''})); });
 it('submits rejection reason',async()=>{ render(<HodIdeaReview/>); await screen.findByText('Secure IoT'); fireEvent.click(within(card('Secure IoT')).getByRole('button',{name:'Reject'})); fireEvent.change(screen.getByLabelText(/Rejection Reason/),{target:{value:'Needs revision'}}); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); await waitFor(()=>expect(api.hodReviewDoctorIdea).toHaveBeenCalledWith(2,{action:'reject',rejection_reason:'Needs revision'})); });
 it('removes approved idea from queue after success',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); await waitFor(()=>expect(screen.queryByText('AI Diagnosis')).toBeNull()); expect(screen.getByText('Secure IoT')).toBeTruthy(); });
 it('closes modal after successful review',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull()); });
 it('shows rejection_reason backend validation error',async()=>{ api.hodReviewDoctorIdea.mockRejectedValue({response:{data:{rejection_reason:['Reason required']}}}); render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Reject'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); expect(await screen.findByText('Reason required')).toBeTruthy(); });
 it('shows backend error field',async()=>{ api.hodReviewDoctorIdea.mockRejectedValue({response:{data:{error:'REVIEW BLOCKED'}}}); render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); expect(await screen.findByText('REVIEW BLOCKED')).toBeTruthy(); });
 it('shows generic review failure',async()=>{ api.hodReviewDoctorIdea.mockRejectedValue(new Error('x')); render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); expect(await screen.findByText('Something went wrong.')).toBeTruthy(); });
 it('keeps idea and modal after failed review',async()=>{ api.hodReviewDoctorIdea.mockRejectedValue(new Error('x')); render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); await screen.findByText('Something went wrong.'); expect(screen.getByText('AI Diagnosis')).toBeTruthy(); expect(screen.getByRole('dialog')).toBeTruthy(); });
 it('disables modal controls while confirming',async()=>{ api.hodReviewDoctorIdea.mockReturnValue(new Promise(()=>{})); render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); fireEvent.click(screen.getByRole('button',{name:'تأكيد'})); await waitFor(()=>expect(screen.getByText('Processing…')).toBeTruthy()); expect(screen.getByRole('button',{name:/Processing/}).disabled).toBe(true); expect(screen.getByRole('button',{name:'Cancel'}).disabled).toBe(true); });
 it('prevents duplicate confirm while request is pending',async()=>{ api.hodReviewDoctorIdea.mockReturnValue(new Promise(()=>{})); render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Approve'})); const btn=screen.getByRole('button',{name:'تأكيد'}); fireEvent.click(btn); fireEvent.click(btn); await waitFor(()=>expect(api.hodReviewDoctorIdea).toHaveBeenCalledTimes(1)); });
 it('resets previous reason when opening another review',async()=>{ render(<HodIdeaReview/>); await screen.findByText('AI Diagnosis'); fireEvent.click(within(card('AI Diagnosis')).getByRole('button',{name:'Reject'})); fireEvent.change(screen.getByLabelText(/Rejection Reason/),{target:{value:'Old reason'}}); fireEvent.click(screen.getByRole('button',{name:'Cancel'})); fireEvent.click(within(card('Secure IoT')).getByRole('button',{name:'Reject'})); expect(screen.getByLabelText(/Rejection Reason/).value).toBe(''); });
});
