# Generated by Django 6.0.3 on 2026-06-28 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0017_studentideaproposal_co_supervisors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional human label', max_length=255)),
                ('committee_type', models.CharField(choices=[('seminar_1', 'Seminar 1'), ('seminar_2', 'Seminar 2'), ('technical', 'Technical Committee'), ('final_discussion', 'Final Discussion')], max_length=25)),
                ('department', models.CharField(choices=[('software_engineering', 'Software Engineering'), ('artificial_intelligence', 'Artificial Intelligence'), ('information_security', 'Information Security'), ('communications', 'Communications'), ('control_robotics', 'Control & Robotics')], max_length=50)),
                ('project_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('graduation_1', 'Graduation 1'), ('graduation_2', 'Graduation 2')], max_length=20)),
                ('semester', models.CharField(default='', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chair', models.ForeignKey(blank=True, help_text='Committee chair (optional at draft stage, but a warning is raised if missing)', limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaired_templates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committee_templates', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Committee members (in addition to the chair)', limit_choices_to={'role': 'doctor'}, related_name='member_in_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField(default=1, help_text='Always 1 in the new design (one committee per template).')),
                ('committee_type', models.CharField(choices=[('seminar_1', 'Seminar 1'), ('seminar_2', 'Seminar 2'), ('technical', 'Technical Committee'), ('final_discussion', 'Final Discussion')], max_length=25)),
                ('department', models.CharField(choices=[('software_engineering', 'Software Engineering'), ('artificial_intelligence', 'Artificial Intelligence'), ('information_security', 'Information Security'), ('communications', 'Communications'), ('control_robotics', 'Control & Robotics')], max_length=50)),
                ('project_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('graduation_1', 'Graduation 1'), ('graduation_2', 'Graduation 2')], max_length=20)),
                ('semester', models.CharField(default='', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applications', models.ManyToManyField(blank=True, help_text='Projects sourced from IdeaApplication (status=registered)', related_name='committees', to='projects.ideaapplication')),
                ('chair', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'doctor'}, related_name='member_in_committees', to=settings.AUTH_USER_MODEL)),
                ('proposals', models.ManyToManyField(blank=True, help_text='Projects sourced from StudentIdeaProposal (status=assigned)', related_name='committees', to='projects.studentideaproposal')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='committees.committeetemplate')),
            ],
            options={
                'ordering': ['template', 'sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='committeetemplate',
            index=models.Index(fields=['committee_type', 'department', 'project_type'], name='committees__committ_49b1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='committeetemplate',
            index=models.Index(fields=['semester'], name='committees__semeste_0a7194_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['committee_type', 'department', 'project_type'], name='committees__committ_b66970_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['status'], name='committees__status_2840db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together={('template', 'sequence_number')},
        ),
    ]
