# Generated by Django 6.0.3 on 2026-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_drop_legacy_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='end_time',
            field=models.TimeField(blank=True, help_text='ساعة النهاية', null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='start_time',
            field=models.TimeField(blank=True, help_text='ساعة البدء', null=True),
        ),
    ]
