# Generated by Django 6.0.3 on 2026-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committee_end_time_committee_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='discussion_duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدة المناقشة بالدقائق (مثال: 15، 30، 45)', null=True),
        ),
    ]
