# Generated by Django 6.0.3 on 2026-07-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_committee_drop_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='doctordateexception',
            new_name='committees__date_ff0247_idx',
            old_name='committees_dde_date_idx',
        ),
        migrations.RenameIndex(
            model_name='doctordateexception',
            new_name='committees__doctor__685143_idx',
            old_name='committees_dde_doc_date_idx',
        ),
        migrations.RenameIndex(
            model_name='doctorweeklyavailability',
            new_name='committees__doctor__140040_idx',
            old_name='committees_dwa_doc_day_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='committees__is_acti_55e122_idx',
            old_name='committees_room_active_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulingrun',
            new_name='committees__committ_349284_idx',
            old_name='committees_sr_type_sem_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulingrun',
            new_name='committees__request_5ce0f0_idx',
            old_name='committees_sr_req_at_idx',
        ),
        migrations.RenameIndex(
            model_name='solversettings',
            new_name='committees__committ_d0e1f7_idx',
            old_name='committees_ss_type_sem_idx',
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together={('template', 'sequence_number')},
        ),
    ]
