# Generated by Django 6.0.3 on 2026-07-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solversettings',
            name='max_committees_per_doctor',
        ),
    ]
