# Generated by Django 6.0.3 on 2026-06-23 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0016_ideaapplication_project_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_summary', models.TextField(blank=True)),
                ('super_admin', models.ForeignKey(limit_choices_to={'is_superuser': True, 'role': 'dean'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('university_id', models.CharField(blank=True, max_length=150)),
                ('project_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='projects.studentideaproposal')),
                ('created_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_import_rows', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='project_imports.importsession')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['super_admin', '-started_at'], name='project_imp_super_a_d18d51_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['status', '-started_at'], name='project_imp_status_c35363_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['session', 'row_number'], name='project_imp_session_74b008_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['session', 'status'], name='project_imp_session_7d7c19_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('session', 'row_number'), name='unique_import_row_per_session'),
        ),
    ]
