# Generated by Django 6.0.3 on 2026-04-28 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_activitylog_taskattachment_taskcomment'),
        ('projects', '0010_ideaapplication_projects_id_student_09f121_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['board', '-created_at'], name='project_man_board_i_3bf52e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor', '-created_at'], name='project_man_actor_i_f2b3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='projectboard',
            index=models.Index(fields=['created_at'], name='project_man_created_fb500a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'status'], name='project_man_board_i_8235f4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='project_man_assigne_5e843b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', '-updated_at'], name='project_man_board_i_de1282_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task', '-created_at'], name='project_man_task_id_9c626e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='project_man_uploade_1f68eb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='project_man_task_id_2897d9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['author', 'created_at'], name='project_man_author__002a94_idx'),
        ),
    ]
