# Generated by Django 6.0.3 on 2026-06-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_activitylog_project_man_board_i_3bf52e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='github_repo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
