# Generated by Django 6.0.3 on 2026-04-27 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_board_id', models.IntegerField(help_text='ID of the project board')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trigger_type', models.CharField(choices=[('project_start', 'Project Start'), ('after_days', 'After X Days'), ('milestone', 'At Milestone'), ('manual', 'Manual Trigger'), ('date', 'Specific Date')], max_length=20)),
                ('trigger_days', models.PositiveIntegerField(blank=True, help_text='Days after project start', null=True)),
                ('trigger_date', models.DateField(blank=True, help_text='Specific date', null=True)),
                ('notify_before_days', models.PositiveIntegerField(default=3, help_text='Notify students X days before due')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('date', 'Date'), ('file', 'File Upload')], max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for select/radio/checkbox')),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflow.workflowstage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='workflow.projectworkflow')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workflow_stages', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflow.workflowstage')),
            ],
            options={
                'ordering': ['stage__order'],
                'unique_together': {('project_workflow', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('software_engineering', 'Software Engineering'), ('artificial_intelligence', 'Artificial Intelligence'), ('information_security', 'Information Security'), ('communications', 'Communications'), ('control_robotics', 'Control & Robotics')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['hod', 'doctor']}, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflow.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workflows', to='workflow.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workflow.workflowstagefield')),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='workflow.workflowstageinstance')),
            ],
            options={
                'unique_together': {('stage_instance', 'field')},
            },
        ),
    ]
