# Generated by Django 6.0.3 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['department', 'status', '-created_at'], name='workflow_wo_departm_4ca7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['created_by', 'status'], name='workflow_wo_created_0fb983_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstage',
            index=models.Index(fields=['template', 'order'], name='workflow_wo_templat_0ed72a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectworkflow',
            index=models.Index(fields=['project_board_id', 'is_active'], name='workflow_pr_project_043194_idx'),
        ),
        migrations.AddIndex(
            model_name='projectworkflow',
            index=models.Index(fields=['template', 'is_active'], name='workflow_pr_templat_b1ec01_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstageinstance',
            index=models.Index(fields=['project_workflow', 'status'], name='workflow_wo_project_630b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstageinstance',
            index=models.Index(fields=['stage', 'status'], name='workflow_wo_stage_i_a42295_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project_board_id',), name='unique_active_workflow_per_project_board'),
        ),
    ]
