# Generated by Django 6.0.3 on 2026-05-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflow_indexes_active_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='max_occurrences',
            field=models.PositiveIntegerField(blank=True, help_text='Max number of recurring instances', null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='recurrence_day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (for weekly)', null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When to stop recurring', null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='recurrence_interval',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Every N units (e.g., every 2 weeks)', null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='recurrence_unit',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workflowstageinstance',
            name='occurrence_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflowstageinstance',
            name='parent_recurrence',
            field=models.ForeignKey(blank=True, help_text='Link to the first instance in the recurrence chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='workflow.workflowstageinstance'),
        ),
    ]
