# Generated by Django 6.0.3 on 2026-06-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_activitylog_project_man_board_i_3bf52e_idx_and_more'),
        ('workflow', '0006_add_scheduled_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectworkflow',
            name='unique_active_workflow_per_project_board',
        ),
        migrations.RemoveIndex(
            model_name='projectworkflow',
            name='workflow_pr_project_043194_idx',
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='project_board',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='project_management.projectboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='recurrence_interval',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Every N units', null=True),
        ),
        migrations.AddIndex(
            model_name='projectworkflow',
            index=models.Index(fields=['project_board', 'is_active'], name='workflow_pr_project_043194_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project_board',), name='unique_active_workflow_per_project_board'),
        ),
        migrations.RemoveField(
            model_name='projectworkflow',
            name='project_board_id',
        ),
    ]
