# Generated by Django 6.0.3 on 2026-06-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_activitylog_project_man_board_i_3bf52e_idx_and_more'),
        ('workflow', '0007_remove_projectworkflow_unique_active_workflow_per_project_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkflow',
            name='project_board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='project_management.projectboard'),
        ),
    ]
