# Generated by Django 6.0.7 on 2026-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_projectworkflow_project_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowfieldresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='workflow_files/'),
        ),
    ]
